export type HealthboxConfig = {
  apiKey: string;
  apiHost?: string;
  defaultCountry?: HealthboxCountry;
  defaultLanguage?: HealthboxLanguage;
};

export type HealthboxRequestOptions = {
   params: any;
}

export enum HealthboxLanguage {
  Bulgarian = 'bg',
  Spanish = 'es',
  Czech = 'cs',
  Danish = 'da',
  German = 'de',
  Estonian = 'et',
  Greek = 'el',
  English = 'en',
  French = 'fr',
  Italian = 'it',
  Latvian = 'lv',
  Lituanian = 'lt',
  Hungarian = 'hu',
  Maltese = 'mt',
  Dutch = 'nl',
  Polish = 'pl',
  Portuguese = 'pt',
  Romanian = 'ro',
  Slovakian = 'sk',
  Slovenian = 'sl',
  Finnish = 'fi',
  Swedish = 'sv',
  Russian = 'ru',
  Arabic = 'ar',
  Norwegian = 'nb',
  Turkish = 'tr',
  Hindi = 'hi',
  Chinese = 'zh',
  Japanese = 'ja',
  Ukrainian = 'uk',
  Icelandic = 'is',
  Swahili = 'sw',
  Indonesian = 'id',
  Croatian = 'hr',
  Serbian = 'sr',
  Hebrew = 'he',
  Armenian = 'hy',
  Malaysian = 'ms',
  Vietnamese = 'vi',
  Catalan = 'ca',
  Korean = 'ko',
  Bengali = 'bn',
}

export enum HealthboxCountry {
   Bulgaria = 'bg',
   Spain = 'es',
   CzechRepublic = 'cz',
   Denmark = 'dk',
   Germany = 'de',
   Estonia = 'ee',
   Greece = 'gr',
   GreatBritain = 'gb',
   France = 'fr',
   Italy = 'it',
   Latvia = 'lv',
   Lithuania = 'lt',
   Hungary = 'hu',
   Malta = 'mt',
   Netherlands = 'nl',
   Poland = 'pl',
   Portugal = 'pt',
   Romania = 'ro',
   Slovakia = 'sk',
   Slovenia = 'si',
   Finland = 'fi',
   Sweden = 'se',
   Russia = 'ru',
   Brazil = 'br',
   Canada = 'ca',
   USA = 'us',
   Switzerland = 'ch',
   Austria = 'at',
   Belgium = 'be',
   Cyprus = 'cy',
   Iceland = 'is',
   Ireland = 'ie',
   Norway = 'no',
   Croatia = 'eu',
   Europe = 'eu',
   SouthAfrica = 'za',
   Luxembourg = 'lu',
   Nigeria = 'ng',
   Turkey = 'tr',
   Andorra = 'ad',
   Argentina = 'ar',
   Armenia = 'am',
   Australia = 'au',
   Bahrain = 'bh',
   Bangladesh = 'bd',
   Belarus = 'by',
   Bosnia = 'ba',
   Cameroon = 'cm',
   Chile = 'cl',
   China = 'cn',
   Cuba = 'cu',
   Egypt = 'eg',
   Guatemala = 'gt',
   India = 'in',
   Israel = 'il',
   Kenya = 'ke',
   Liechtenstein = 'li',
   Malaysia = 'my',
   NewZealand = 'nz',
   Pakistan = 'pk',
   Panama = 'pa',
   Peru = 'pe',
   Philippines = 'ph',
   Serbia = 'rs',
   Singapore = 'sg',
   SouthKorea = 'kr',
   Tanzania = 'tz',
   Thailand = 'th',
   Tunisia = 'tn',
   Uganda = 'ug',
   UAE = 'ae',
   Uruguay = 'uy',
   Venezuela = 've',
   Vietnam = 'vn',
   Zimbabwe = 'zw',
}
